[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory with the static files (Vite builds to 'build' not 'dist')
  publish = "build"
  
  # Directory for Netlify Functions
  functions = "netlify/functions"
  
  # Environment variables for secrets scanning
  environment = { SECRETS_SCAN_ENABLED = "false" }

# Redirect all traffic to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API endpoint redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "max-age=31536000"